### ISSUE TITLE
feat: Mini "istio" on application layer

### ISSUE THREAD

**Issue by henninghaakonsen** [navikt/token-support#108]
Uten istio er det vanskelig å sikre seg mot at kun spesifikke applikasjoner kaller tjenestene man lager. I familie har vi implementert en interceptor som sjekker om azp i tokenet finnes i en liste av ACCEPTED_CLIENTS(client id'er). Jeg foreslår å legge til denne logikken i dette biblioteket slik at alle kan definere en liste av ACCEPTED_CLIENTS per registration slik at endepunktet kun tillater trafikk fra spesifikke apper.

**Comment by jan-olaveide** [comment]
This has nothing to do with OIDC as such and should be handled locally.
