### ISSUE TITLE
feat: "Duplicate key" - cookies with the same key

### ISSUE THREAD

**Issue by LarsAndreasNav** [navikt/token-support#139]
Biblioteket baserer seg på at det kun er én cookie med navnet man konfigurerer opp. Dette fungerer til de fleste formål, men "in the wild" har vi oppdaget at mange interne brukere har to cookies som begge heter ID_token, men med forskjellige domains (adeo.no og nais.adeo.no). Disse kommer fra OpenAM. Alle kall fra disse brukerne feiler mot vår backend. Selv om vi faktisk kun trenger Azure-validering i det aktuelle endepunktet.

Ideell oppførsel sett fra min side, ville vært om biblioteket validerer alle tokens med det gitte navnet, og bare velger et token å gå videre med hvis det er flere gyldige.

**Comment by ybelMekk** [comment]
see: https://github.com/navikt/token-support/pull/221
That will solve the issue, but is it enough @tommytroen ?

**Comment by ybelMekk** [comment]
@LarsAndreasNav
Is this still an issue?

**Comment by tommytroen** [comment]
possible solutions leads to unpredictable behaviour, as there are possible workarounds we wont fix this issue now
