### ISSUE TITLE
OAuth Token, Validated as OIDC

### ISSUE THREAD

**Issue by TheMather1** [navikt/token-support#171]
When processing OAuth tokens, they are attempted validated as OIDC, resulting in a BadJWTException being thrown over missing sub claims.

**Comment by ybelMekk** [comment]
Ok. i see this one.
Maskinporten tokens do not contain `sub`claim
Example:
`  "aud": "https://tt02.altinn.no/maskinporten-api/",
  "scope": "altinn:maskinporten/delegationschemes.read altinn:maskinporten/delegationschemes.write",
  "iss": "https://ver2.maskinporten.no/",
  "client_amr": "private_key_jwt",
  "consumer_prefix": [
    "if2018",
    "nav"
  ],
  "token_type": "Bearer",
  "exp": 1592384617,
  "iat": 1592381017,
  "client_id": "oidc_nav_portal_testkonsument",
  "jti": "F2c6MyAKlheVNHsXztmwD2n3yD7caybzOYfdyapF3fY",
  "consumer": {
    "authority": "iso6523-actorid-upis",
    "ID": "0192:889640782"
  }
}`

**Comment by ybelMekk** [comment]
Not sure this is a bug checking the code, @tronghn do u know if a server can set a list of claims, to be checked or if claims can be ignored?

**Comment by ybelMekk** [comment]
Yes, agree, i will start to take a look at possible solutions in the end of the day, and start to investigate further changes. please feel free to join with you comments :D @tommytroen

**Comment by ybelMekk** [comment]
issue: https://github.com/navikt/token-support/tree/release/oauthtoken_validated_as_oidctoken
