### ISSUE TITLE
Support for expirythreshold in token-validation-ktor

### ISSUE THREAD

**Issue by Robert-Larsen** [navikt/token-support#179]
It would have been very nice to be able to set expirythreshold also in the ktor-module, not only in the Spring-module. Any plans to add this feature?

**Comment by tronghn** [comment]
It's unlikely that we'll look at this right now as vacation approaches. You're welcome to add a pull request if you want to, otherwise it'll have to wait for a bit.

**Comment by Robert-Larsen** [comment]
I have implemented a proposal for a solution, but it seems that I dot not have push-access.

**Comment by ybelMekk** [comment]
> I have implemented a proposal for a solution, but it seems that I dot not have push-access.

Gave you write access to allow you to push your branch and proposal changes @Robert-Larsen
