### ISSUE TITLE
feat: Support for meta annotations and superclasses/interfaces in token-support-core/JwtTokenAnnotationHandler

### ISSUE THREAD

**Issue by tommytroen** [navikt/token-support#195]
#191 implements support for meta annotations and annotations on superclasses/interfaces with the `SpringJwtTokenAnnotationHandler` using the Spring utility class `AnnotationsUtils`. Ideally this should be supported in the core module in the `JwtTokenAnnotationHandler` without dependency on Spring classes, using JDK methods only.

**Comment by jan-olaveide** [comment]
Much ado about marginal gain,
