### ISSUE TITLE
feat: Dynamic claims

### ISSUE THREAD

**Issue by tiafiring** [navikt/token-support#22]
Når vi tar i bruk accesstokens utstedt av AzureAD (client credentials grant) for server-til-server-integrasjon får vi behov for å kunne sjekke dynamiske claims med annotasjonen "ProtectedWithClaims" for å sikre at kun spesifiserte apper har tilgang til api'et. Kan dere vurdere om dette er noe dere ønsker å støtte i biblioteket? 

Se gjerne diskusjon på slack: https://nav-it.slack.com/archives/CFTR8QE3T/p1549446169077300

**Comment by ybelMekk** [comment]
Think this one is related to issue: https://github.com/navikt/token-support/issues/108. Basically asking for an interceptor that checks who can talk to the applikasjon on application layer. I could think this is out of the scope for this lib!?
