### ISSUE TITLE
Propose refactor: make token-support java 8 compliant

### ISSUE THREAD

**Issue by patped** [navikt/token-support#294]
Making the project java 8 compliant will (possibly) make it easier for older applications to migrate from another security-framework.

This means that you loose the ability to use newer java features but this doesn't mean much at this point in time, as you can see in the proposed patch (ref:1). The patch is considered work in progress, but it should give an indication of how small this change really is.

It may be something I'm not aware of or haven't considered, but I'm willing to "do the heavy lifting" if the propose gets accepted.

Ref.
1: https://github.com/patped/token-support/commit/c0e54c54859d99ac7ced5868451c7730aec1a655

**Comment by patped** [comment]
The only thing that I'm aware of that making the project java 8 compliant trouble in the future is that caffeine v.3 is dropping support for java 8 (ref:1).

Ref.
1: https://github.com/ben-manes/caffeine/commit/e1f96e018b23183baaf29e900310cfc35c2f7567

**Comment by tommytroen** [comment]
> The only thing that I'm aware that can cause trouble in the future is that caffeine v.3 is dropping support for java 8 (ref:1).
> 
> Ref.
> 1: [ben-manes/caffeine@e1f96e0](https://github.com/ben-manes/caffeine/commit/e1f96e018b23183baaf29e900310cfc35c2f7567)

This can potentially be a dealbreaker, we are a bit reluctant moving the entire code base back to java 8, we are however considering other approaches for this. How far away from java 11 are you?

**Comment by tommytroen** [comment]
@patped ☝️

**Comment by patped** [comment]
> > The only thing that I'm aware that can cause trouble in the future is that caffeine v.3 is dropping support for java 8 (ref:1).
> > Ref.
> > 1: [ben-manes/caffeine@e1f96e0](https://github.com/ben-manes/caffeine/commit/e1f96e018b23183baaf29e900310cfc35c2f7567)
> 
> This can potentially be a dealbreaker, we are a bit reluctant moving the entire code base back to java 8, we are however considering other approaches for this. How far away from java 11 are you?

I understand you are a bit reluctant on promising supporting java 8 in to the future and putting the geene back in bottle can be hard. I'm "happily" maintaining my own fork when java 8 support becomes bottleneck for the project. That said, I'm eager to hear what other approaches you're thinking of?

At this moment in time we are stuck at java 8u101 and I can't really put java 11 on the roadmap yet with all the old dialogarena and modig libraries that we are dependent on.

**Comment by patped** [comment]
Here is a reply from ben-manes saying that the v.2 of caffeine will be supported for as long as needed, but it will not getting any new feature releases.

https://github.com/ben-manes/caffeine/issues/499

**Comment by tommytroen** [comment]
@patped lets have a chat on monday?

**Comment by patped** [comment]
> @patped lets have a chat on monday?

After the meeting with @tommytroen we agreed that supporting java 8 will be revisited if the demand picks up as my initial need is no longer necessary after @tommytroen helped us upgrade to java 11.
