### ISSUE TITLE
feat: Remove stacktrace from normal info-logs: Invalid token for issuer (priority:low)

### ISSUE THREAD

**Issue by siljee** [navikt/token-support#31]
Vurder gjerne å fjerne stacktrace på loggen om at bruker sin token er blitt invalid. 
Dette er vanlig flyt når bruker enten ikke har logget seg på eller når token er utløpt og jeg ser ikke behovet for å ha med stacktrace. Stacktracen får meg ofte til å tro at det er skjedd noe galt når jeg utvikler lokalt. 

Dette er ikke noe kritisk eller viktig, kun et irritasjonsmoment :) 

`12:18:35 [xec-2] INFO OIDCTokenValidationFilter : Invalid token for issuer [azuread, expires at Fri Apr 26 17:47:25 CEST 2019]
no.nav.security.oidc.exceptions.OIDCTokenValidatorException: Token validation failed
    at no.nav.security.oidc.validation.OIDCTokenValidator.assertValidToken(OIDCTokenValidator.java:49)
    at no.nav.security.oidc.validation.OIDCTokenValidator.assertValidToken(OIDCTokenValidator.java:40)`

**Comment by ybelMekk** [comment]
Er dette fortsatt en issue som dere ser som et irritasjonsmoment? @siljee

**Comment by ybelMekk** [comment]
class is renamed from `OIDCTokenValidatorException`: to `JwtTokenValidatorException`

**Comment by ybelMekk** [comment]
see: https://github.com/navikt/token-support/pull/219

**Comment by siljee** [comment]
Lenge siden jeg har irritert meg over dette nå 😄
