### ISSUE TITLE
Vurdere retry ved utstedelse av tokens ved definierte feil

### ISSUE THREAD

**Issue by blommish** [navikt/token-support#394]
Hei!

Hadde det vært en idè å legge inn retry når man utsteder tokens, for å unngå eks feilet "Connection Reset".
Burde vel også vurdere hvilke andre feil som kan være interessante å håndtere, samt hvordan, kanskje retry en gang er tilstrekkelig eller burde man ha exponential backoff? Tror ikke vi trenger exponential backoff. 

https://nav-it.slack.com/archives/C5KUST8N6/p1629368229194400

**Comment by jan-olaveide** [comment]
Omsider fått tatt en kikk på denne. Enig at dette burde være funksjonalitet  i token-support, men en midlertidig workaround er ganske enkel, hvertfall når man bruker Spring Boot. 
token-client-spring [registrerer](https://github.com/navikt/token-support/blob/master/token-client-spring/src/main/kotlin/no/nav/security/token/support/client/spring/oauth2/OAuth2ClientConfiguration.kt#L48)  en RestTemplate basert implementasjon av [OAuth2HttpClient](https://github.com/navikt/token-support/blob/master/token-client-core/src/main/java/no/nav/security/token/support/client/core/http/OAuth2HttpClient.java). 
Denne kan enkelt overstyres i lokal konfigurasjon, som [her](https://github.com/navikt/aap-soknad-api/blob/main/src/main/kotlin/no/nav/aap/api/config/GlobalBeanConfig.kt#L230-L259). Her brukes en WebClient basert variant som bruker en RetryBackoffSpec, men her kan man bruke hvilken klient og retry-mekanisme man måtte ønske, et naturlig annet alternativ vil kunne være  RestTemplate og Spring Retry. Merk at siden default-implemntasjonen ikke er en _good spring citizen_ som holder seg unna om en annen implementasjon eksisterer, må denne lokale annoteres med _@Primary_ for at de ikke skal gå i beina på hverandre. Dette vil endres i senere releaser. (Annoteringene @ConditionalOnNotProd er bare for min testing i dev, og er ikke nødvendige) @blommish

**Comment by blommish** [comment]
Lukker den her då brukere kan overstyre `OAuth2HttpClient` som Jan-Olav nevner
Mulig den kommer in en gang i token-support
