### ISSUE TITLE
Dependency til kotlin-stdlib-jdk8 alltid inkludert

### ISSUE THREAD

**Issue by mrsladek** [navikt/token-support#521]
token-client-core drar inn alltid kotlin-stdlib-jdk8 med.

Er den dependencien nødvendig?

**Comment by jan-olaveide** [comment]
Godt spørsmål, skal sjekke

**Comment by mrsladek** [comment]
Den kommer inn gjennom `token-support` modul som er far modul til bl.an `token-client-core` og `token-validation-core`

**Comment by jan-olaveide** [comment]
Fikset i 2.1.1 nå
