### ISSUE TITLE
JWT Token validation enabled på applikasjonsnivå validerer til en viss grad tokens i ekskluderte klasser

### ISSUE THREAD

**Issue by noraness** [navikt/token-support#721]
Vi har kall fra eksterne med autentiseringstoken som ikke er jwt. Disse er ekskludert fra JWT Token validation (forsøkt både med @Unprotected og ignore på annotasjon i mainmetode). Likevel ser vi følgende warning i loggene: «Received exception when attempting to extract and parse token from Authorization header» (pga missing dot delimiters).

**Comment by jan-olaveide** [comment]
Kanskje et dumt spørsmål, men hvorfor kaller eksterne et åpent endepunkt med et ikke-jwt token?
