### ISSUE TITLE
Støtte for java 21

### ISSUE THREAD

**Issue by hensol** [navikt/token-support#794]
Har dere mulighet til å lage en versjon på java 21?

**Comment by jan-olaveide** [comment]
Har jo det, men er det noen utfordringer med å kjøre på 17?
Vi vil ikke vedlikeholde 2 versjoner, så om vi forlater 17 og går til 21 vil all nyutvikling skje der. Ved eventuelle bugfikser vil vi da tvinge klienter over på 21, vet ikke om vi ønsker det så raskt?

**Comment by hensol** [comment]
> Har jo det, men er det noen utfordringer med å kjøre på 17? Vi vil ikke vedlikeholde 2 versjoner, så om vi forlater 17 og går til 21 vil all nyutvikling skje der. Ved eventuelle bugfikser vil vi da tvinge klienter over på 21, vet ikke om vi ønsker det så raskt?

Jo, er enig i at det kanskje er litt tidlig å kreve at alle skal over på 21.
Jeg får skrive meg rundt mockk problemene jeg har i testene mine :)
`mockk<TokenValidationContext>()` klager på bytecode inkompatibilitet....
